name: Monthly Patching

on:
  schedule:
    - cron:  '0 12 1 * *'

env:
  GOPRIVATE: github.com/takt-corp/*

jobs:
  check:
    name: Patch
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global url."https://takt-engineering-bot:${{ secrets.BOT_TOKEN }}@github.com".insteadOf "https://github.com"
          git config --global user.email "takt-engineering-bot@takt.io"
          git config --global user.name "Takt Engineering Bot"

      - uses: actions/setup-go@v4
        with:
          check-latest: true

      - run: git checkout -b patching-${{ github.run_id }}

      - run: make deps

      - uses: golangci/golangci-lint-action@v3

      - run: gh pr create -B develop --title 'Security Patching' --body 'Updating dependencies to latest versions.'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
